CREATE TABLE IF NOT EXISTS coverage_queue (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    record_id  INT NOT NULL,
    added_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
